# Generated by Django 3.1 on 2022-01-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20220123_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
